#!/usr/bin/env sh

/usr/local/bin/etcdctl --endpoints=zhangchaojie.net:2379 watch --prefix mac -- sh -c '
echo ==========
echo ETCD_WATCH_EVENT_TYPE $ETCD_WATCH_EVENT_TYPE
echo ETCD_WATCH_REVISION $ETCD_WATCH_REVISION
echo ETCD_WATCH_VALUE $ETCD_WATCH_VALUE
echo ETCD_WATCH_KEY $ETCD_WATCH_KEY
echo ==========
/usr/local/bin/${ETCD_WATCH_KEY:1:${#ETCD_WATCH_KEY}-2} ${ETCD_WATCH_VALUE:1:${#ETCD_WATCH_VALUE}-2} || exit 0
'